# -*- coding: utf-8 -*-
"""Mini project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gKUO1jq9yOL_wWcmria05LUE9tJQ1v5a
"""

# ================================
# 1. IMPORT LIBRARIES
# ================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from xgboost import XGBRegressor

# ================================
# 2. LOAD DATA
# ================================

df = pd.read_csv("/content/Groundwater India Data.csv")

print("Dataset shape:", df.shape)
display(df.head())

# ================================
# 3. CLEAN & FEATURE ENGINEER
# ================================

df = df.rename(columns={'t  kmnpnn]2m': 't2m_avg'})
df['datetime'] = pd.to_datetime(df['datetime'])
df = df.sort_values(['station_id', 'datetime']).reset_index(drop=True)

# clip extreme outlier readings (~299 stations have datum-shift errors)
q01, q99 = df['target'].quantile([0.01, 0.99])
df['target'] = df['target'].clip(q01, q99)

# lag + rolling features
df['prev_target'] = df.groupby('station_id')['target'].shift(1)
df['rolling_rainfall_3'] = df.groupby('station_id')['rainfall'].transform(lambda s: s.rolling(3, min_periods=1).mean())
df = df.dropna(subset=['prev_target']).reset_index(drop=True)

features = ['month', 'rainfall', 't2m_avg', 't2m_max', 't2m_min',
            'latitude', 'longitude', 'wellDepth', 'wellAquiferType_encoded',
            'State_encoded', 'District_encoded', 'prev_target', 'rolling_rainfall_3']

X = df[features]
y = df['target']

print("Rows after cleaning:", len(df))
display(X.head())

# ================================
# 4. TRAIN MODELS
# ================================

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf = RandomForestRegressor(n_estimators=100, max_depth=10, n_jobs=-1, random_state=42)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
print(f"Random Forest - R2: {r2_score(y_test, rf_pred):.3f}  RMSE: {np.sqrt(mean_squared_error(y_test, rf_pred)):.3f}")

xgb = XGBRegressor(n_estimators=150, max_depth=6, learning_rate=0.1, n_jobs=-1, random_state=42)
xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)
print(f"XGBoost       - R2: {r2_score(y_test, xgb_pred):.3f}  RMSE: {np.sqrt(mean_squared_error(y_test, xgb_pred)):.3f}")

# pick the better one - just keep it as a plain variable, nothing saved to disk
model = xgb if r2_score(y_test, xgb_pred) > r2_score(y_test, rf_pred) else rf
print("\nUsing model:", "XGBoost" if model is xgb else "Random Forest")

importances = pd.Series(model.feature_importances_, index=features).sort_values(ascending=False)
plt.figure(figsize=(8,5))
sns.barplot(x=importances.values, y=importances.index)
plt.title("Feature Importance")
plt.tight_layout()
plt.show()

# ================================
# 5. RISK THRESHOLDS (kept as a plain dict in memory)
# ================================

thresholds = {}
for station, grp in df.groupby('station_id'):
    vals = grp['target']
    thresholds[station] = {
        'safe_max': vals.quantile(0.5),
        'declining_max': vals.quantile(0.8),
    }

print(f"Computed thresholds for {len(thresholds)} stations")

# ================================
# 6. TEST A PREDICTION - pick a well-populated station
# ================================

station_counts = df['station_id'].value_counts()
print(station_counts.head(10))

station = station_counts.index[0]   # station with the most historical readings
station_hist = df[df['station_id'] == station].sort_values('datetime')
row = station_hist.iloc[-1]
th = thresholds[station]

X_input = pd.DataFrame([{
    'month': 7, 'rainfall': 5.0, 't2m_avg': 28.0, 't2m_max': 34.0, 't2m_min': 24.0,
    'latitude': row['latitude'], 'longitude': row['longitude'], 'wellDepth': row['wellDepth'],
    'wellAquiferType_encoded': row['wellAquiferType_encoded'],
    'State_encoded': row['State_encoded'], 'District_encoded': row['District_encoded'],
    'prev_target': row['target'], 'rolling_rainfall_3': row['rolling_rainfall_3'],
}])[features]

pred = model.predict(X_input)[0]
risk = "Safe" if pred <= th['safe_max'] else ("Declining" if pred <= th['declining_max'] else "Critical")

print(f"Station: {station}  ({len(station_hist)} historical readings)")
print(f"Predicted level: {pred:.2f}   Risk: {risk}")

plt.figure(figsize=(10,4))
plt.plot(station_hist['datetime'], station_hist['target'], color='#2E5C9A', linewidth=1, label='Historical readings')
plt.axhline(th['safe_max'], color='green', linestyle='--', label='Safe threshold')
plt.axhline(th['declining_max'], color='orange', linestyle='--', label='Declining threshold')
plt.scatter([station_hist['datetime'].iloc[-1]], [pred], color='red', s=80, zorder=5, label='New prediction')
plt.title(f"Groundwater Level Trend — {station}")
plt.legend(fontsize=8)
plt.tight_layout()
plt.show()

# ================================
# 7. RISK DISTRIBUTION ACROSS ALL STATIONS
# ================================

latest = df.sort_values('datetime').groupby('station_id').tail(1)

risk_counts = {'Safe': 0, 'Declining': 0, 'Critical': 0}
for _, r in latest.iterrows():
    th = thresholds[r['station_id']]
    if r['target'] <= th['safe_max']:
        risk_counts['Safe'] += 1
    elif r['target'] <= th['declining_max']:
        risk_counts['Declining'] += 1
    else:
        risk_counts['Critical'] += 1

print(risk_counts)

plt.figure(figsize=(6,4))
plt.bar(risk_counts.keys(), risk_counts.values(), color=['green','orange','red'])
plt.title("Well Risk Distribution — All Stations")
plt.tight_layout()
plt.show()

